# -*- coding: utf-8 -*-
"""climate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U6jgSCBQd5M3SQi1dKH97z-6_5pkXaFi
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px

from google.colab import files
uploaded = files.upload()

data = pd.read_csv("DailyDelhiClimateTrain.csv")
print(data.head())
print(data.describe())

print(data.info())

figure = px.line(data, x="date",
                 y="meantemp",
                 title='Mean Temperature in Delhi Over the Years')
figure.show()

figure = px.line(data, x="date",
                 y="humidity",
                 title='Humidity in Delhi Over the Years')
figure.show()

figure = px.line(data, x = "date",
                  y="wind_speed",
                  title="Wind Speed in Delhi Over the Years")
figure.show()

"""Till 2015, the wind speed was higher during monsoons (August & September) and retreating monsoons (December & January). After 2015, there were no anomalies in wind speed during monsoons.

**Now let’s have a look at the relationship between temperature and humidity:**
"""

figure = px.scatter(data_frame = data, x = "humidity",
                    y = "meantemp", size = "meantemp",
                    trendline = "ols",
                    title = "Relationship Between Temperature and Humidity")

figure.show()

"""There’s a negative correlation between temperature and humidity in Delhi. It means higher temperature results in low humidity and lower temperature results in high humidity."""

data["date"] = pd.to_datetime(data["date"], format = '%Y-%m-%d')
data['year'] = data['date'].dt.year
data["month"] = data["date"].dt.month
print(data.head())

plt.style.use('fivethirtyeight')
plt.figure(figsize=(10, 5))
plt.title("Temperature Change in Delhi Over the Years")
sns.lineplot(data = data, x='month', y='meantemp', hue='year')
plt.show()

"""Although 2017 was not the hottest year in the summer, we can see a rise in the average temperature of Delhi every year.

# *Forecasting Weather using Python*

Now let’s move to the task of weather forecasting. I will be using the Facebook prophet model for this task. The Facebook prophet model is one of the best techniques for time series forecasting. If you have never used this model before, you can install it on your system by using the command mentioned below in your command prompt or terminal:
Forecasting Weather using Python
pip install prophet
"""

pip install prophet

"""The prophet model accepts time data named as “ds”, and labels as “y”. So let’s convert the data into this format:"""

forecast_data = data.rename(columns = {"date": "ds",
                                       "meantemp": "y"})
print(forecast_data)

"""Now below is how we can use the Facebook prophet model for weather forecasting using Python:"""

from prophet import Prophet
from prophet.plot import plot_plotly, plot_components_plotly
model = Prophet()
model.fit(forecast_data)
forecasts = model.make_future_dataframe(periods=365)
predictions = model.predict(forecasts)
plot_plotly(model, predictions)

